Remove BLI_bfile.c from build process. It is unused, and currently throws error C4013
(ie. previous commit works sweetly ;)

git-svn-id: https://svn.blender.org/svnroot/bf-blender/trunk/blender@32585 954f8c5b-7b00-dc11-b283-0030488c597c